# Generated by Django 2.0.3 on 2019-05-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='notes',
            new_name='topping1',
        ),
    ]
