# Generated by Django 2.0.3 on 2019-05-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190504_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='productprice',
            new_name='price',
        ),
    ]
