# Generated by Django 2.0.3 on 2019-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20190504_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='single', max_length=64),
            preserve_default=False,
        ),
    ]
