# Generated by Django 2.0.3 on 2019-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20190504_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
