# Generated by Django 2.0.3 on 2019-05-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190507_0758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
