# Generated by Django 2.0.3 on 2019-05-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190508_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='orders.Status'),
        ),
    ]
