# Generated by Django 2.0.3 on 2019-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='price_lg',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_sm',
            field=models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
