# Generated by Django 2.0.3 on 2019-05-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190504_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_lg',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_sm',
            new_name='price_small',
        ),
    ]
