# Generated by Django 2.0.3 on 2019-05-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190504_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterUniqueTogether(
            name='kind',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set(),
        ),
    ]
