# Generated by Django 2.0.3 on 2019-05-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190504_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
