# Generated by Django 2.2.1 on 2019-05-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='cheese.png', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='regular.png', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='sicilian.png', upload_to='product_pics'),
        ),
    ]
