# Generated by Django 2.2.1 on 2019-05-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190515_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='image',
            field=models.ImageField(default='cheese.png', upload_to='kind_pics'),
        ),
    ]
